swagger: "2.0"
info:
  title: "Go Messages API"
  description: "API REST básica en Go para manejar mensajes"
  version: "1.0.0"
host: YOUR-PROJECT-ID.appspot.com # e.g., immune-institute.appspot.com
x-google-endpoints:
  - name: YOUR-PROJECT-ID.appspot.com # e.g., immune-institute-293912.appspot.com
    allowCors: true
schemes:
  - https
produces:
  - "application/json"
consumes:
  - "application/json"
paths:
  /messages:
    get:
      summary: "Obtener todos los mensajes"
      description: "Lista todos los mensajes"
      operationId: listMessages
      responses:
        "200":
          description: "Lista de mensajes"
          schema:
            type: array
            items:
              $ref: "#/definitions/Message"
    post:
      summary: "Crear un nuevo mensaje"
      description: "Crea un nuevo mensaje"
      operationId: createMessage
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/NewMessage"
      responses:
        "201":
          description: "Mensaje creado exitosamente"
          schema:
            $ref: "#/definitions/Message"
        "400":
          description: "Solicitud inválida"

  "/messages/{id}":
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
    get:
      summary: "Obtener un mensaje específico por ID"
      description: "Obtiene un mensaje específico"
      operationId: getMessage
      responses:
        "200":
          description: "Mensaje encontrado"
          schema:
            $ref: "#/definitions/Message"
        "404":
          description: "Mensaje no encontrado"
    put:
      summary: "Actualizar un mensaje por ID"
      description: "Actualiza un mensaje"
      operationId: updateMessage
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/NewMessage"
      responses:
        "200":
          description: "Mensaje actualizado"
          schema:
            $ref: "#/definitions/Message"
        "400":
          description: "Solicitud inválida"
        "404":
          description: "Mensaje no encontrado"
    delete:
      summary: "Eliminar un mensaje por ID"
      description: "Elimina un mensaje"
      operationId: deleteMessage
      responses:
        "204":
          description: "Mensaje eliminado"
        "404":
          description: "Mensaje no encontrado"

  # This endpoint for serving HTML might be better handled directly by Cloud Run
  # or a separate frontend service, but can be proxied by Endpoints if needed.
  /:
    get:
      summary: "Página HTML de inicio"
      description: "Página HTML de inicio"
      operationId: serveHTML
      produces:
        - text/html
      responses:
        "200":
          description: OK

x-google-backend:
  # This should be the full HTTPS URL of your deployed 'go-rest-api' Cloud Run service.
  address: YOUR-CLOUD-RUN-ENDPOINT # e.g., https://go-rest-api-abcdef1234-ew.a.run.app

# --- Schema Definitions for API Request/Response Bodies ---
definitions:
  Message:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      content:
        type: "string"
    required:
      - "id"
      - "content"
  NewMessage:
    type: "object"
    properties:
      content:
        type: "string"
    required:
      - "content"
