apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web
  labels:
    app: go-web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web
      version: v1
  template:
    metadata:
      labels:
        app: go-web
        version: v1
    spec:
      containers:
      - name: productpage
        image: docker.io/arnausenserrich/webserver:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
