apiVersion: v1
kind: Service
metadata:
  name: pub-webserver
spec:
  selector:
    app: go-web
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  externalTrafficPolicy: Local
  type: LoadBalancer
